name: sctructurizr-cli  # feel free to pick your own name

on: [push, pull_request]

jobs:
  structurizr-cli:
    runs-on: ubuntu-latest
    name: Run structurizr-cli
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run structurizr-cli action
        uses: aidmax/structurizr-cli-action@v1
        id: test
        with:
          id: 93153
          key: 5eb0abb6-4aea-4ec5-b7fc-12be0dd6224b
          secret: 746671bd-3af3-4584-8541-90f716b0adaa
          workspace: RDFtoCSV

          # optional parameters
          # The Structurizr API URL (optional; defaults to https://api.structurizr.com)
          # The passphrase to use (optional; only required if client-side encryption enabled on the workspace)
          url: https://api.structurizr.com
